# Generated by Django 3.2.5 on 2021-07-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('studentname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('cnfrmpassword', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('phone', models.IntegerField(max_length=30)),
            ],
        ),
    ]
